# Generated by Django 3.2.6 on 2021-09-03 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210902_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updat_date',
        ),
        migrations.AddField(
            model_name='task',
            name='uuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
